imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

services:
    custom.elastica_formatter:
        class: SocialWallBundle\Monolog\Formatter\ElasticaFormatter
        arguments: [ "@security.token_storage", "%elasticsearch_monolog_index%", "record" ]

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [ 'FOSUserBundle']
    filters:
        cssrewrite: ~
    assets:
        admin_base_js:
            inputs:
                - 'bundles/socialwall/lib/neon/js/jquery-1.11.0.min.js'
                - 'bundles/socialwall/lib/neon/js/gsap/main-gsap.js'
                - 'bundles/socialwall/lib/neon/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js'
                - 'bundles/socialwall/lib/neon/js/bootstrap.js'
                - 'bundles/socialwall/lib/neon/js/joinable.js'
                - 'bundles/socialwall/lib/neon/js/resizeable.js'
                - 'bundles/socialwall/lib/neon/js/neon-api.js'
                - 'bundles/socialwall/lib/neon/js/neon-custom.js'
            output: "compiled/js/admin-base.js"
        admin_base_css:
            inputs:
                - 'bundles/socialwall/lib/neon/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css'
                - 'bundles/socialwall/lib/neon/css/font-icons/entypo/css/entypo.css'
                - 'bundles/socialwall/lib/neon/css/bootstrap.css'
                - 'bundles/socialwall/lib/neon/css/neon-core.css'
                - 'bundles/socialwall/lib/neon/css/neon-theme.css'
                - 'bundles/socialwall/lib/neon/css/neon-forms.css'
                - 'bundles/socialwall/lib/neon/css/custom.css'
            output: "compiled/css/admin-base.css"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: SocialWallBundle\Entity\User
