social_wall_default:
    resource: "@SocialWallBundle/Controller/DefaultController.php"
    type:     annotation

social_wall_admin:
    resource: "@SocialWallBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
