social_wall_default:
    resource: "@SocialWallBundle/Controller/DefaultController.php"
    type:     annotation

social_wall_admin:
    resource: "@SocialWallBundle/Controller/Admin/DefaultController.php"
    type:     annotation
    prefix:   /admin

social_wall_admin_facebook:
    resource: "@SocialWallBundle/Controller/Admin/FacebookController.php"
    type:     annotation
    prefix:   /admin/facebook

social_wall_admin_instagram:
    resource: "@SocialWallBundle/Controller/Admin/InstagramController.php"
    type:     annotation
    prefix:   /admin/instagram

social_wall_analytics:
    resource: "@SocialWallBundle/Controller/Front/LogController.php"
    type:     annotation
