parameters:
    facebook_helper.class: "SocialWallBundle\Services\FacebookHelper"
    instagram_helper.class: "SocialWallBundle\Services\InstagramHelper"
    faye_curl_adapter.class: "Nc\FayeClient\Adapter\CurlAdapter"
    faye_client.class: "Nc\FayeClient\Client"
    social_media_listener.class: "SocialWallBundle\EventListener\SocialMediaListener"

services:
    social_media_helper:
        abstract: true
        calls:
            - [setSymfonySecret, ["%secret%"]]

    facebook_helper:
        class: "%facebook_helper.class%"
        arguments: [ %facebook_id%, %facebook_secret%, %facebook_app_token%, @session ]
        parent: social_media_helper

    instagram_helper:
        class: "%instagram_helper.class%"
        arguments: [ %instagram_id%, %instagram_secret% ]
        parent: social_media_helper

    faye_curl_adapter:
        class: %faye_curl_adapter.class%

    faye_client:
        class: "%faye_client.class%"
        arguments: [ @faye_curl_adapter, "http://localhost:3000" ]

    social_media_listener:
        class: "%social_media_listener.class%"
        arguments: [ @facebook_helper, @faye_client ]
        tags:
            - { name: doctrine.orm.entity_listener }
